# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_classification.core.ipynb.

# %% auto 0
__all__ = ['get_users_labels']

# %% ../../nbs/01_classification.core.ipynb 3
import pandas as pd

# %% ../../nbs/01_classification.core.ipynb 4
def get_users_labels(path, label_col='R_Pain_Int', drop_ixs=None):
    data = pd.read_excel(path)
    labels = data['R_Pain_Int'].dropna()
    users = data['ID'].dropna()
    users.drop(drop_ixs, inplace=True)
    labels.drop(drop_ixs, inplace=True)
    return users, labels
