project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    contents: 
        - section: data
          contents: 
          - 00_data.core.ipynb
          - 00b_data.visualization.ipynb
        - section: classification
          contents:
          - 01_classification.core.ipynb

metadata-files: [nbdev.yml, sidebar.yml]
