project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    collapse-level: 1
    contents: 
        - index.ipynb
        - section: data
          contents: 
          - 00_data.ipynb
        - section: models
          contents:
          - 01_models.ipynb
        - section: preprocessing
          contents:
          - 02_preprocessing.ipynb
        - section: utils
          contents:
          - 03_utils.ipynb
        - section: training
          contents:
          - 04_training.ipynb
        - section: tutorial
          contents:
          - 05a_Monitosed_EOEC.ipynb
          - 05b_Monitosed.ipynb
          - 05c_Monitosed_Explanations.ipynb

metadata-files: [nbdev.yml]
